version: "3.8"

services:
    # PocketBase Backend
    pocketbase:
        image: ghcr.io/muchobien/pocketbase:latest
        container_name: pocketbase
        restart: unless-stopped
        command:
            [
                "--serve",
                "--http=0.0.0.0:8090",
                "--dir=/pb_data",
                "--publicDir=/pb_public",
            ]
        ports:
            - "8090:8090"
        volumes:
            - pocketbase_data:/pb_data
            - pocketbase_public:/pb_public
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:8090/api/health",
                ]
            interval: 5s
            timeout: 5s
            retries: 5

    # React Frontend - Development
    frontend-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: react-frontend-dev
        restart: unless-stopped
        ports:
            - "3000:3000"
        environment:
            - BACKEND_API_URL_BASE=http://pocketbase:8090/api/
            - NODE_ENV=development
        depends_on:
            pocketbase:
                condition: service_healthy
        volumes:
            - ./src:/app/src
            - ./public:/app/public
            - /app/node_modules
        profiles:
            - dev

    # React Frontend - Production
    frontend-prod:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        container_name: react-frontend-prod
        restart: unless-stopped
        ports:
            - "3000:80"
        environment:
            - BACKEND_API_URL_BASE=http://pocketbase:8090/api/
            - NODE_ENV=production
        depends_on:
            pocketbase:
                condition: service_healthy
        profiles:
            - prod

    # Nginx Reverse Proxy (Production only)
    nginx:
        image: nginx:alpine
        container_name: nginx-proxy
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - frontend-prod
            - pocketbase
        profiles:
            - prod

volumes:
    pocketbase_data:
    pocketbase_public:

networks:
    default:
        name: fullstack-network
